## ----------------------------------------------------------------------------
## ..:: Mysql POD / Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: hackazon
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: hackazon
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: Default1234!
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: hackazon/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-gsfs-k8s
---
## ----------------------------------------------------------------------------
## ..:: Hackazon POD / Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: hackazon
  namespace: hackazon
  labels:
    app: hackazon
spec:
  type: ClusterIP
  ports:
  - name: hackazon-80
    port: 80
    protocol: TCP
  selector:
      app: hackazon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon
  namespace: hackazon
  labels:
    app: hackazon
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackazon
      version: v1
  template:
    metadata:
      labels:
        app: hackazon
        version: v1
    spec:
      containers:
      - env:
        - name: service_name
          value: hackazon
        image:  mutzel/all-in-one-hackazon
        imagePullPolicy: IfNotPresent
        name: hackazon
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: hackazon-persistent-storage
          mountPath: /var/www/hackazon
          subPath: hackazon/hackazon
      volumes:
      - name: hackazon-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-gsfs-k8s
---
## ----------------------------------------------------------------------------
## ..:: NGINX KIC VS Configuration for Hackazon ::..
##-----------------------------------------------------------------------------
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: hackazon-vs
  namespace: hackazon
spec:
  host: hackazon.f5-udf.com
  upstreams:
  - name: hackazon
    service: hackazon
    port: 80
  routes:
  - path: /
    action:
      pass: hackazon
