apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hackazon
data:
  protect .conf: |
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
     
        server {
            listen       80;
            server_name  hackazon-nap.f5-udf.com;
            proxy_http_version 1.1;
     
            app_protect_enable on;
            app_protect_security_log_enable on;
            app_protect_security_log "/etc/nginx/log-default.json" syslog:server=127.0.0.1:514;

            location / {     
                client_max_body_size 0;
                default_type text/html;
                proxy_pass http://127.0.0.1:3000$request_uri;
                proxy_set_header Host $host;
            }
        }
    }
