apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hackazon
data:
  protect.conf: |
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        sendfile        on;
        keepalive_timeout  65;
     
        server {
            listen       8080;
            server_name  hackazon-nap.f5-udf.com;
            proxy_http_version 1.1;
     
            app_protect_enable on;
            app_protect_security_log_enable on;
            app_protect_security_log "/etc/nginx/log-default.json" syslog:server=127.0.0.1:514;

            location / {     
                client_max_body_size 0;
                default_type text/html;
                proxy_pass http://127.0.0.1:80$request_uri;
                proxy_set_header Host $host;
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-waf
  namespace: hackazon
data:
  waf-policy.json: |
    {
    "name": "nginx-policy",
    "template": { "name": "POLICY_TEMPLATE_NGINX_BASE" },
    "applicationLanguage": "utf-8",
    "enforcementMode": "blocking",
    		"signature-sets": [
    			{
    				"name": "All Signatures",
    				"block": true,
    				"alarm": true
    			},
    			{
    				"name": "High Accuracy Signatures",
    				"block": true,
    				"alarm": true
    			}
    		],
    "blocking-settings": {
        "violations": [
            {
    					"name": "VIOL_RATING_NEED_EXAMINATION",
    					"alarm": true,
    					"block": true
    				},
            {
            "name": "VIOL_HTTP_PROTOCOL",
            "alarm": true,
            "block": true,
            "learn": true
            },
            {
            "name": "VIOL_FILETYPE",
            "alarm": true,
            "block": true,
            "learn": true
            },
            {
            "name": "VIOL_COOKIE_MALFORMED",
            "alarm": true,
            "block": false,
            "learn": false
            }
        ],
        "http-protocols": [{
            "description": "Body in GET or HEAD requests",
            "enabled": true,
            "learn": true,
            "maxHeaders": 20,
            "maxParams": 500
        }],
    		"filetypes": [
    			{
    				"name": "*",
    				"type": "wildcard",
    				"allowed": true,
    				"responseCheck": true
    			}
        ],
    		"data-guard": {
    			"enabled": true,
    			"maskData": true,
    			"creditCardNumbers": true,
    			"usSocialSecurityNumbers": true
    		},
    		"cookies": [
    			{
    				"name": "*",
    				"type": "wildcard",
    				"accessibleOnlyThroughTheHttpProtocol": true,
    				"attackSignaturesCheck": true,
    				"insertSameSiteAttribute": "strict"
    			}
    		],
        "evasions": [{
            "description": "%u decoding",
            "enabled": true,
            "learn": false,
            "maxDecodingPasses": 2
        }]}
    }
    
---
---
## ----------------------------------------------------------------------------
## ..:: Hackazon POD / Service Configuration ::..
##-----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: hackazon-nap
  namespace: hackazon
  labels:
    app: hackazon-nap
spec:
  type: ClusterIP
  ports:
  - name: hackazon-nap
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
      app: hackazon-nap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon-nap
  namespace: hackazon
  labels:
    app: hackazon-nap
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackazon-nap
      version: v1
  template:
    metadata:
      labels:
        app: hackazon-nap
        version: v1
    spec:
      containers:
      - image:  mutzel/all-in-one-hackazon
        imagePullPolicy: IfNotPresent
        name: hackazon-nap
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: hackazon-persistent-storage
          mountPath: /var/www/hackazon
          subPath: hackazon/hackazon-nap
      - image: registry.f5-udf.com:5000/nginx-nap:latest
        imagePullPolicy: Always
        name: hackazon-nginx-app-protect
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 443
        volumeMounts:
        - mountPath: /etc/nginx/waf
          readOnly: true
          name: nginx-waf
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: nginx-config
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - CAP_NET_BIND_SERVICE
          procMount: Default
          runAsUser: 0
          runAsGroup: 0
          privileged: true
      volumes:
      - name: hackazon-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-gsfs-k8s
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-waf
        configMap:
          name: nginx-waf
      imagePullSecrets:
        - name: regcred
          
---
## ----------------------------------------------------------------------------
## ..:: NGINX KIC VS Configuration for Hackazon ::..
##-----------------------------------------------------------------------------
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: hackazon-nap-vs
  namespace: hackazon
spec:
  host: hackazon-nap.f5-udf.com
  upstreams:
  - name: hackazon-nap
    service: hackazon-nap
    port: 8080
  routes:
  - path: /
    action:
      pass: hackazon-nap